[package]
name = "litesvm-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
litesvm.workspace = true
solana-sdk.workspace = true
spl-token-2022.workspace = true
solana-program.workspace = true

[dev-dependencies]
test-log.workspace = true
solana-program.workspace = true
