on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Rustup install
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v3.0.3/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$GITHUB_PATH:$PATH"

      - name: Build test programs
        run: cd crates/litesvm/test_programs && cargo build-sbf

      - name: Run tests
        run: cargo test --features precompiles
        env:
          RUST_BACKTRACE: 1

      - name: Run SPL tests
        run: cd crates/token && cargo test --features token-2022
        env:
          RUST_BACKTRACE: 1

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Rustup install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
