name: release NodeJS

on:
  push:
    tags:
      - "node-v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: yarn
          cache-dependency-path: crates/node-litesvm/yarn.lock

      - name: Install dependencies
        run: |
          cd crates/node-litesvm/
          corepack enable
          yarn install

      - name: Disable napi GitHub release
        run: echo "NAPI_SKIP_GITHUB_RELEASE=true" >> $GITHUB_ENV

      - name: Create npm dirs
        run: cd crates/node-litesvm/ && yarn napi create-npm-dirs

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: node-build.yml
          path: crates/node-litesvm/artifacts

      - name: Move artifacts
        run: cd crates/node-litesvm/ && yarn artifacts

      - name: Compile TypeScript
        run: cd crates/node-litesvm/ && yarn build:js

      - name: List packages
        run: cd crates/node-litesvm/ && ls -R ./npm

      - name: Publish
        env:
          NAPI_SKIP_GITHUB_RELEASE: true
        run: |
          cd crates/node-litesvm/
          TAG_NAME="${GITHUB_REF_NAME}"

          if printf "%s" "$TAG_NAME" | grep "^node-v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            npm publish --access public
          elif printf "%s" "$TAG_NAME" | grep "^node-v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
            npm publish --tag next --access public
          else
            echo "Not a release, skipping publish (tag: $TAG_NAME)"
          fi
